// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosCFG.Models;

namespace PosCFG.Migrations
{
    [DbContext(typeof(PosCFGDbContext))]
    [Migration("20200728152131_change")]
    partial class change
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PosCFG.Models.SystemPOS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConnectGroup")
                        .HasColumnType("int");

                    b.Property<int>("ControlCheckSum")
                        .HasColumnType("int");

                    b.Property<int>("ControlGroup")
                        .HasColumnType("int");

                    b.Property<string>("Paquete")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("ParameterGroup")
                        .HasColumnType("int");

                    b.Property<int>("ParameterReload")
                        .HasColumnType("int");

                    b.Property<int>("ParameterVersion")
                        .HasColumnType("int");

                    b.Property<int>("ParmConnChecksum")
                        .HasColumnType("int");

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.Property<int>("ProgramReload")
                        .HasColumnType("int");

                    b.Property<int>("ProgramVersion")
                        .HasColumnType("int");

                    b.Property<int>("TerminalChecksum")
                        .HasColumnType("int");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TranConnChecksum1")
                        .HasColumnType("int");

                    b.Property<int>("TranConnChecksum2")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TerminalID")
                        .IsUnique();

                    b.ToTable("SystemPOSs");
                });

            modelBuilder.Entity("PosCFG.Models.Terminal", b =>
                {
                    b.Property<string>("TerminalID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Custom1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderLine3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParmConnectTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suspend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TranConnectTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TerminalID");

                    b.ToTable("Terminals");
                });

            modelBuilder.Entity("PosCFG.Models.SystemPOS", b =>
                {
                    b.HasOne("PosCFG.Models.Terminal", "Terminal")
                        .WithOne("SystemPOS")
                        .HasForeignKey("PosCFG.Models.SystemPOS", "TerminalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
